// <auto-generated />
using System;
using Lesson28.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lesson28.Migrations
{
    [DbContext(typeof(QuotesContext))]
    [Migration("20211107130346_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0-rc.2.21480.5");

            modelBuilder.Entity("Lesson28.Models.Quotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Некий Великий Ноунейм №1",
                            InsertDate = new DateTime(2021, 11, 7, 18, 3, 45, 891, DateTimeKind.Local).AddTicks(311),
                            Text = "Цитата №1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Некий Великий Ноунейм №2",
                            InsertDate = new DateTime(2021, 11, 7, 18, 3, 45, 891, DateTimeKind.Local).AddTicks(321),
                            Text = "Цитата №2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Некий Великий Ноунейм №3",
                            InsertDate = new DateTime(2021, 11, 7, 18, 3, 45, 891, DateTimeKind.Local).AddTicks(322),
                            Text = "Цитата №3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Некий Великий Ноунейм №4",
                            InsertDate = new DateTime(2021, 11, 7, 18, 3, 45, 891, DateTimeKind.Local).AddTicks(323),
                            Text = "Цитата №4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Некий Великий Ноунейм №5",
                            InsertDate = new DateTime(2021, 11, 7, 18, 3, 45, 891, DateTimeKind.Local).AddTicks(324),
                            Text = "Цитата №5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
